#cloud-config
users:
  - name: "{default_user}"
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
    hashed_passwd: "{password_hash}"
    ssh_authorized_keys:
      - "{public_key}"

disable_root: false
allow_public_ssh_keys: true

chpasswd:
  expire: False

ssh_pwauth: True